name: xeofs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>3.8
  - numpy
  - pandas
  - xarray
  - conda
  - scikit-learn
  - yaml
  - matplotlib
  - seaborn
  - pip:
    - sphinxawesome-theme
    - git+https://github.com/sphinx-gallery/sphinx-gallery.git@master
    - xeofs
