name: xeofs
channels:
  - conda-forge
  - nodefaults  # https://github.com/readthedocs/readthedocs.org/issues/9527
dependencies:
  - python==3.11
  - numpy
  - pandas
  - xarray
  - conda
  - scikit-learn
  - statsmodels
  - dask
  - yaml
  - matplotlib
  - seaborn
  - cartopy
  - ipython
  - ipykernel
  - rpy2
  - sphinx-gallery
  - sphinx-design
  - sphinx-copybutton
  - nbsphinx
  - pydata-sphinx-theme
  - sphinx
  - nbconvert
  - pip:
    - xeofs
