name: xeofs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.8
  - numpy
  - pandas
  - xarray
  - conda
  - scikit-learn
  - yaml
  - matplotlib
  - pip:
    - sphinxawesome-theme
    - sphinx-gallery
    - xeofs
